export const menus = [
  {
    id: 1,
    name: "Enso’s Secret Beef Ramen",
    desc: "159",
    price: 159,
    category: "noodle",
    is_available: true,
    banner: "https://enso.app/menu/beef-ramen.jpg",
    created_at: "2025-07-21T12:00:00Z",
    updated_at: "2025-09-01T09:30:00Z",
  },
  {
    id: 2,
    name: "Truffle Unagi Don",
    desc: "Grilled eel glazed with sweet soy, served over premium Japanese rice with truffle aroma.",
    price: 289,
    category: "rice",
    is_available: true,
    banner: "https://enso.app/menu/unagi-don.jpg",
    created_at: "2025-07-21T12:05:00Z",
    updated_at: "2025-09-01T09:31:00Z",
  },
  {
    id: 3,
    name: "Salmon Sashimi Deluxe",
    desc: "Freshly sliced salmon sashimi served with wasabi and soy sauce.",
    price: 199,
    category: "sashimi",
    is_available: true,
    banner: "https://enso.app/menu/salmon-sashimi.jpg",
    created_at: "2025-07-21T12:10:00Z",
    updated_at: "2025-09-01T09:32:00Z",
  },
  {
    id: 4,
    name: "Dragon Roll Sushi",
    desc: "Shrimp tempura roll topped with avocado and unagi sauce.",
    price: 259,
    category: "sushi",
    is_available: true,
    banner: "https://enso.app/menu/dragon-roll.jpg",
    created_at: "2025-07-21T12:15:00Z",
    updated_at: "2025-09-01T09:33:00Z",
  },
  {
    id: 5,
    name: "Spicy Tuna Roll",
    desc: "Classic sushi roll with fresh tuna, spicy mayo, and cucumber.",
    price: 189,
    category: "sushi",
    is_available: false,
    banner: "https://enso.app/menu/spicy-tuna-roll.jpg",
    created_at: "2025-07-21T12:20:00Z",
    updated_at: "2025-09-01T09:34:00Z",
  },
];

export const category = [
  "All",
  "noodles",
  "Sushi & Sashimi",
  "Appetizers",
  "Desserts",
  "Drinks",
];